name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
#    - name: Run tests
#      run: swift test -v
  deploy:
    runs-on: macos
    steps:
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Show Firebase CLI version
        run: firebase --version
