name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
#    - name: Run tests
#      run: swift test -v
  deploy:
    runs-on: macos
    steps:
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Show Firebase CLI version
        run: firebase --version
      - name: Install Publish
        run: |
          git clone https://github.com/JohnSundell/Publish.git
          cd Publish
          make
          cd ..
      - name: Generate Site
        run: publish generate
#       - name: Generate Not Found Page
#         run: mv Output/404/index.html Output/404.html
