name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
#    - name: Run tests
#      run: swift test -v
    - name: Install Firebase CLI
      run: npm i -g firebase-tools
    - name: Show Firebase CLI version
      run: firebase --version
    - name: pwd 1
      run: |
        pwd
        ls 
    - name: Install Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make
        cd ..
    - name: Generate Site
      run: publish generate
    - name: Generate Not Found Page
      run: mv Output/404/index.html Output/404.html
    - name: Firebase deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --project alvarez-technologies
